---
title: 'EDS 230: Week 6 Assignment: Diffusion'
author: "Juliet Cohen, Scout Leonard, Peter Menzies"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: false
    number_sections: yes
header-includes:
  - \setlength{\parindent}{1em}
  - \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries
library(tidyverse)
library(deSolve)
library(here)

#source scripts
source(here("R/diffusion.R"))
```

# Intial

```{r}
# run our diffusion model (iterative difference equation) with initial concentration of 10, for 8 timestep (size 1m), and 10 space steps (size 1s)
# using diffusion parameters 0.5 s/m2, 10 m2
result = diff1(initialC = 10, 
               nx = 10, 
               dx = 1, 
               nt = 8, 
               dt = 1, 
               D = 0.5, 
               area = 10)
# initialC = initial concentration (mg/L)
# nx = number of discrete segments
# dx = length of each segment (m)
# nt = # of discrete time intervals
# dt = seconds in each time interval

# a list is returned with our 3 data frames for concentration (conc), qin and qout
result

# used filled contour to plot results
head(result$conc)
filled.contour(result$conc, xlab="Time", ylab="Distance")

# or if you prefer this orientation (Distance on x axis)
# filled.contour(t(result$conc), ylab="Time", xlab="Distance")
```

# Change parameters (increase initial concentration & increase seconds in each time interval)

```{r}
# changes diffusivity and other parameters particularly
# diffusivity, dx and dt

res1 = diff1(initialC = 30, # changed the initial concentration parameter from 10 mg/L to 30 mg/L
          nx = 10, 
          dx = 1,
          nt = 8,
          dt = 3, # changed the seconds in each time interval parameter from 1 second to 3 seconds
          D = 0.5, 
          area = 10)

# previous:
# result = diff1(initialC = 10, 
               # nx = 10, 
               # dx = 1, 
               # nt = 8, 
               # dt = 1, 
               # D = 0.5, 
               # area = 10)

# initialC = initial concentration (mg/L)
# nx = number of discrete segments
# dx = length of each segment (m)
# nt = # of discrete time intervals
# dt = seconds in each time interval

filled.contour(res1$conc, xlab="Time", ylab="Distance")

# we can also see how much material moved from place to place each time step
#filled.contour(res$qin, xlab="Time", ylab="Distance")
```

```{r}
# changes diffusivity and other parameters particularly
# diffusivity, dx and dt

res2 = diff1(initialC = 10, 
               nx = 2, #decreased the length of each segment from 10 m to 2 m
               dx = 1, 
               nt = 6, #decreased the number of time intervals from 8 to 6
               dt = 1, 
               D = 0.5, 
               area = 10)

# previous:
# result = diff1(initialC = 10, 
               # nx = 10, 
               # dx = 1, 
               # nt = 8, 
               # dt = 1, 
               # D = 0.5, 
               # area = 10)

# initialC = initial concentration (mg/L)
# nx = number of discrete segments
# dx = length of each segment (m)
# nt = # of discrete time intervals
# dt = seconds in each time interval

filled.contour(res2$conc, xlab="Time", ylab="Distance")

# we can also see how much material moved from place to place each time step
#filled.contour(res$qin, xlab="Time", ylab="Distance")
```